print("                                          Resume              ")
print("")
print("")


fname=input(" ")
email=input("Email:")
address=input("Address:")
Mobile=input("Mobile No:")
print("")
print("")


print("       I want to succeed in an environment of growth and excellence to meet personal and organiztional goals.")
print("")
print("")

print("Educational Qualifications:")
print("")
print("")
print("    BOARD      "+"             YEAR        "+"            SCHOOL/COLLEGE")
print("")
print("Krishna Universty"+"           2018        "+"           A.N.R College")
print("Intermediate      "+"          2015        "+"          vidhyalaya Jr.college")
print("SSC      "+"                   2013        "+"          Trveni IIT School")
print("")
print("")
print("")
print("Interests:")
print("           .......")
print("           .......")
print("           .......")
print("")
print("")
print("     I here by declare that all the above given information is true to the best of my Knowledge and belief.")
      
print("")
print("")
place=input("Place:")
print("")
date=input("Date:")
print("                                                                     kona Sai Venkata Lalith Kumar")
